/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * DateTime scalar type
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * DateTime scalar type
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  MenuCategory: "COFFEE" | "FOOD"
  OrderStatus: "COMPLETED" | "PENDING"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  MenuItem: { // root type
    category: NexusGenEnums['MenuCategory']; // MenuCategory!
    id: number; // Int!
    name: string; // String!
    price: number; // Float!
  }
  Mutation: {};
  Order: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    itemIds: number[]; // [Int!]!
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
    userId: number; // Int!
  }
  Query: {};
  User: { // root type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  MenuItem: { // field return type
    category: NexusGenEnums['MenuCategory']; // MenuCategory!
    id: number; // Int!
    name: string; // String!
    price: number; // Float!
  }
  Mutation: { // field return type
    createMenuItem: NexusGenRootTypes['MenuItem']; // MenuItem!
    createOrder: NexusGenRootTypes['Order']; // Order!
    createUser: NexusGenRootTypes['User']; // User!
    deleteMenuItem: NexusGenRootTypes['MenuItem'] | null; // MenuItem
    deleteOrder: NexusGenRootTypes['Order'] | null; // Order
    deleteUser: NexusGenRootTypes['User'] | null; // User
    updateMenuItem: NexusGenRootTypes['MenuItem']; // MenuItem!
    updateOrder: NexusGenRootTypes['Order']; // Order!
    updateUser: NexusGenRootTypes['User']; // User!
  }
  Order: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    itemIds: number[]; // [Int!]!
    items: NexusGenRootTypes['MenuItem'][]; // [MenuItem!]!
    status: NexusGenEnums['OrderStatus']; // OrderStatus!
    user: NexusGenRootTypes['User'] | null; // User
    userId: number; // Int!
  }
  Query: { // field return type
    menu: NexusGenRootTypes['MenuItem'][]; // [MenuItem!]!
    menuItem: NexusGenRootTypes['MenuItem']; // MenuItem!
    order: NexusGenRootTypes['Order']; // Order!
    orders: NexusGenRootTypes['Order'][]; // [Order!]!
    user: NexusGenRootTypes['User']; // User!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  User: { // field return type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    orders: NexusGenRootTypes['Order'][]; // [Order!]!
  }
}

export interface NexusGenFieldTypeNames {
  MenuItem: { // field return type name
    category: 'MenuCategory'
    id: 'Int'
    name: 'String'
    price: 'Float'
  }
  Mutation: { // field return type name
    createMenuItem: 'MenuItem'
    createOrder: 'Order'
    createUser: 'User'
    deleteMenuItem: 'MenuItem'
    deleteOrder: 'Order'
    deleteUser: 'User'
    updateMenuItem: 'MenuItem'
    updateOrder: 'Order'
    updateUser: 'User'
  }
  Order: { // field return type name
    createdAt: 'DateTime'
    id: 'Int'
    itemIds: 'Int'
    items: 'MenuItem'
    status: 'OrderStatus'
    user: 'User'
    userId: 'Int'
  }
  Query: { // field return type name
    menu: 'MenuItem'
    menuItem: 'MenuItem'
    order: 'Order'
    orders: 'Order'
    user: 'User'
    users: 'User'
  }
  User: { // field return type name
    email: 'String'
    id: 'Int'
    name: 'String'
    orders: 'Order'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createMenuItem: { // args
      category: NexusGenEnums['MenuCategory']; // MenuCategory!
      name: string; // String!
      price: number; // Float!
    }
    createOrder: { // args
      items: number[]; // [Int!]!
      userId: number; // Int!
    }
    createUser: { // args
      email: string; // String!
      name: string; // String!
    }
    deleteMenuItem: { // args
      id: number; // Int!
    }
    deleteOrder: { // args
      id: number; // Int!
    }
    deleteUser: { // args
      id: number; // Int!
    }
    updateMenuItem: { // args
      category?: NexusGenEnums['MenuCategory'] | null; // MenuCategory
      id: number; // Int!
      name?: string | null; // String
      price?: number | null; // Float
    }
    updateOrder: { // args
      id: number; // Int!
      status: NexusGenEnums['OrderStatus']; // OrderStatus!
    }
    updateUser: { // args
      email?: string | null; // String
      id: number; // Int!
      name?: string | null; // String
    }
  }
  Query: {
    menuItem: { // args
      id: number; // Int!
    }
    order: { // args
      id: number; // Int!
    }
    user: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}