/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import type { GqlScalar } from "grats";
import type { DateTime as DateTimeInternal } from "./models/scalars.ts";
import { GraphQLSchema, GraphQLObjectType, GraphQLList, GraphQLNonNull, GraphQLUnionType, GraphQLInt, GraphQLString, GraphQLFloat, GraphQLEnumType, GraphQLInterfaceType, GraphQLScalarType } from "graphql";
import { menu as queryMenuResolver, menuItem as queryMenuItemResolver, createCoffee as mutationCreateCoffeeResolver, createDessert as mutationCreateDessertResolver, deleteMenuItem as mutationDeleteMenuItemResolver, updateCoffee as mutationUpdateCoffeeResolver, updateDessert as mutationUpdateDessertResolver } from "./models/menu.ts";
import { items as orderItemsResolver, user as orderUserResolver, order as queryOrderResolver, orders as queryOrdersResolver, ordersByStatus as queryOrdersByStatusResolver, createOrder as mutationCreateOrderResolver, deleteOrder as mutationDeleteOrderResolver, updateOrder as mutationUpdateOrderResolver } from "./models/order.ts";
import { orders as userOrdersResolver, user as queryUserResolver, users as queryUsersResolver, createUser as mutationCreateUserResolver, deleteUser as mutationDeleteUserResolver, updateUser as mutationUpdateUserResolver } from "./models/user.ts";
export type SchemaConfig = {
    scalars: {
        DateTime: GqlScalar<DateTimeInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const SugarLevelType: GraphQLEnumType = new GraphQLEnumType({
        description: "Sugar level for coffee",
        name: "SugarLevel",
        values: {
            HIGH: {
                value: "HIGH"
            },
            LOW: {
                value: "LOW"
            },
            MEDIUM: {
                value: "MEDIUM"
            },
            NONE: {
                value: "NONE"
            }
        }
    });
    const FoodType: GraphQLInterfaceType = new GraphQLInterfaceType({
        description: "Food interface with common fields",
        name: "Food",
        fields() {
            return {
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                price: {
                    name: "price",
                    type: GraphQLFloat
                }
            };
        }
    });
    const CoffeeType: GraphQLObjectType = new GraphQLObjectType({
        name: "Coffee",
        description: "Coffee menu item",
        fields() {
            return {
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                origin: {
                    name: "origin",
                    type: GraphQLString
                },
                price: {
                    name: "price",
                    type: GraphQLFloat
                },
                sugarLevel: {
                    name: "sugarLevel",
                    type: SugarLevelType
                }
            };
        },
        interfaces() {
            return [FoodType];
        }
    });
    const DessertType: GraphQLObjectType = new GraphQLObjectType({
        name: "Dessert",
        description: "Dessert menu item",
        fields() {
            return {
                calories: {
                    name: "calories",
                    type: GraphQLFloat
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                price: {
                    name: "price",
                    type: GraphQLFloat
                }
            };
        },
        interfaces() {
            return [FoodType];
        }
    });
    const MenuItemType: GraphQLUnionType = new GraphQLUnionType({
        name: "MenuItem",
        description: "Menu item union type",
        types() {
            return [CoffeeType, DessertType];
        }
    });
    const DateTimeType: GraphQLScalarType = new GraphQLScalarType({
        name: "DateTime",
        ...config.scalars.DateTime
    });
    const OrderStatusType: GraphQLEnumType = new GraphQLEnumType({
        description: "Order status",
        name: "OrderStatus",
        values: {
            CANCELLED: {
                value: "CANCELLED"
            },
            COMPLETED: {
                value: "COMPLETED"
            },
            PENDING: {
                value: "PENDING"
            }
        }
    });
    const UserType: GraphQLObjectType = new GraphQLObjectType({
        name: "User",
        description: "User information",
        fields() {
            return {
                email: {
                    name: "email",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                orders: {
                    name: "orders",
                    type: new GraphQLList(new GraphQLNonNull(OrderType)),
                    resolve(source) {
                        return userOrdersResolver(source);
                    }
                }
            };
        }
    });
    const OrderType: GraphQLObjectType = new GraphQLObjectType({
        name: "Order",
        description: "Order information",
        fields() {
            return {
                createdAt: {
                    name: "createdAt",
                    type: DateTimeType
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                itemIds: {
                    name: "itemIds",
                    type: new GraphQLList(new GraphQLNonNull(GraphQLInt))
                },
                items: {
                    name: "items",
                    type: new GraphQLList(new GraphQLNonNull(MenuItemType)),
                    resolve(source) {
                        return orderItemsResolver(source);
                    }
                },
                status: {
                    name: "status",
                    type: OrderStatusType
                },
                user: {
                    name: "user",
                    type: UserType,
                    resolve(source) {
                        return orderUserResolver(source);
                    }
                },
                userId: {
                    name: "userId",
                    type: GraphQLInt
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                menu: {
                    name: "menu",
                    type: new GraphQLList(new GraphQLNonNull(MenuItemType)),
                    resolve() {
                        return queryMenuResolver();
                    }
                },
                menuItem: {
                    name: "menuItem",
                    type: MenuItemType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return queryMenuItemResolver(args.id);
                    }
                },
                order: {
                    name: "order",
                    type: OrderType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return queryOrderResolver(args.id);
                    }
                },
                orders: {
                    name: "orders",
                    type: new GraphQLList(new GraphQLNonNull(OrderType)),
                    resolve() {
                        return queryOrdersResolver();
                    }
                },
                ordersByStatus: {
                    name: "ordersByStatus",
                    type: new GraphQLList(new GraphQLNonNull(OrderType)),
                    args: {
                        status: {
                            type: new GraphQLNonNull(OrderStatusType)
                        }
                    },
                    resolve(_source, args) {
                        return queryOrdersByStatusResolver(args.status);
                    }
                },
                user: {
                    name: "user",
                    type: UserType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return queryUserResolver(args.id);
                    }
                },
                users: {
                    name: "users",
                    type: new GraphQLList(new GraphQLNonNull(UserType)),
                    resolve() {
                        return queryUsersResolver();
                    }
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                createCoffee: {
                    name: "createCoffee",
                    type: CoffeeType,
                    args: {
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        origin: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        price: {
                            type: new GraphQLNonNull(GraphQLFloat)
                        },
                        sugarLevel: {
                            type: new GraphQLNonNull(SugarLevelType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateCoffeeResolver(args.name, args.price, args.sugarLevel, args.origin);
                    }
                },
                createDessert: {
                    name: "createDessert",
                    type: DessertType,
                    args: {
                        calories: {
                            type: new GraphQLNonNull(GraphQLFloat)
                        },
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        price: {
                            type: new GraphQLNonNull(GraphQLFloat)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateDessertResolver(args.name, args.price, args.calories);
                    }
                },
                createOrder: {
                    name: "createOrder",
                    type: OrderType,
                    args: {
                        items: {
                            type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GraphQLInt)))
                        },
                        userId: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateOrderResolver(args.userId, args.items);
                    }
                },
                createUser: {
                    name: "createUser",
                    type: UserType,
                    args: {
                        email: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateUserResolver(args.name, args.email);
                    }
                },
                deleteMenuItem: {
                    name: "deleteMenuItem",
                    type: MenuItemType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationDeleteMenuItemResolver(args.id);
                    }
                },
                deleteOrder: {
                    name: "deleteOrder",
                    type: OrderType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationDeleteOrderResolver(args.id);
                    }
                },
                deleteUser: {
                    name: "deleteUser",
                    type: UserType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationDeleteUserResolver(args.id);
                    }
                },
                updateCoffee: {
                    name: "updateCoffee",
                    type: CoffeeType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        name: {
                            type: GraphQLString
                        },
                        origin: {
                            type: GraphQLString
                        },
                        price: {
                            type: GraphQLFloat
                        },
                        sugarLevel: {
                            type: SugarLevelType
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateCoffeeResolver(args.id, args.name, args.price, args.sugarLevel, args.origin);
                    }
                },
                updateDessert: {
                    name: "updateDessert",
                    type: DessertType,
                    args: {
                        calories: {
                            type: GraphQLFloat
                        },
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        name: {
                            type: GraphQLString
                        },
                        price: {
                            type: GraphQLFloat
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateDessertResolver(args.id, args.name, args.price, args.calories);
                    }
                },
                updateOrder: {
                    name: "updateOrder",
                    type: OrderType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        status: {
                            type: new GraphQLNonNull(OrderStatusType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateOrderResolver(args.id, args.status);
                    }
                },
                updateUser: {
                    name: "updateUser",
                    type: UserType,
                    args: {
                        email: {
                            type: GraphQLString
                        },
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        name: {
                            type: GraphQLString
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateUserResolver(args.id, args.name, args.email);
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        mutation: MutationType,
        types: [DateTimeType, OrderStatusType, SugarLevelType, MenuItemType, FoodType, CoffeeType, DessertType, MutationType, OrderType, QueryType, UserType]
    });
}
