/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import type { GqlScalar } from "grats";
import type { DateTime as DateTimeInternal } from "./models/scalars.ts";
import { GraphQLSchema, GraphQLObjectType, GraphQLList, GraphQLNonNull, GraphQLEnumType, GraphQLInt, GraphQLString, GraphQLFloat, GraphQLScalarType } from "graphql";
import { menu as queryMenuResolver, menuItem as queryMenuItemResolver, menuItems as queryMenuItemsResolver, createMenuItem as mutationCreateMenuItemResolver, deleteMenuItem as mutationDeleteMenuItemResolver, updateMenuItem as mutationUpdateMenuItemResolver } from "./models/menu.ts";
import { items as orderItemsResolver, user as orderUserResolver, order as queryOrderResolver, orders as queryOrdersResolver, ordersByStatus as queryOrdersByStatusResolver, createOrder as mutationCreateOrderResolver, deleteOrder as mutationDeleteOrderResolver, updateOrder as mutationUpdateOrderResolver } from "./models/order.ts";
import { orders as userOrdersResolver, user as queryUserResolver, users as queryUsersResolver, createUser as mutationCreateUserResolver, deleteUser as mutationDeleteUserResolver, updateUser as mutationUpdateUserResolver } from "./models/user.ts";
export type SchemaConfig = {
    scalars: {
        DateTime: GqlScalar<DateTimeInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const MenuCategoryType: GraphQLEnumType = new GraphQLEnumType({
        description: "Menu category",
        name: "MenuCategory",
        values: {
            COFFEE: {
                value: "COFFEE"
            },
            FOOD: {
                value: "FOOD"
            }
        }
    });
    const MenuItemType: GraphQLObjectType = new GraphQLObjectType({
        name: "MenuItem",
        description: "Menu item information",
        fields() {
            return {
                category: {
                    name: "category",
                    type: MenuCategoryType
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                price: {
                    name: "price",
                    type: GraphQLFloat
                }
            };
        }
    });
    const DateTimeType: GraphQLScalarType = new GraphQLScalarType({
        name: "DateTime",
        ...config.scalars.DateTime
    });
    const OrderStatusType: GraphQLEnumType = new GraphQLEnumType({
        description: "Order status",
        name: "OrderStatus",
        values: {
            CANCELLED: {
                value: "CANCELLED"
            },
            COMPLETED: {
                value: "COMPLETED"
            },
            PENDING: {
                value: "PENDING"
            }
        }
    });
    const UserType: GraphQLObjectType = new GraphQLObjectType({
        name: "User",
        description: "User information",
        fields() {
            return {
                email: {
                    name: "email",
                    type: GraphQLString
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                name: {
                    name: "name",
                    type: GraphQLString
                },
                orders: {
                    name: "orders",
                    type: new GraphQLList(new GraphQLNonNull(OrderType)),
                    resolve(source) {
                        return userOrdersResolver(source);
                    }
                }
            };
        }
    });
    const OrderType: GraphQLObjectType = new GraphQLObjectType({
        name: "Order",
        description: "Order information",
        fields() {
            return {
                createdAt: {
                    name: "createdAt",
                    type: DateTimeType
                },
                id: {
                    name: "id",
                    type: GraphQLInt
                },
                itemIds: {
                    name: "itemIds",
                    type: new GraphQLList(new GraphQLNonNull(GraphQLInt))
                },
                items: {
                    name: "items",
                    type: new GraphQLList(new GraphQLNonNull(MenuItemType)),
                    resolve(source) {
                        return orderItemsResolver(source);
                    }
                },
                status: {
                    name: "status",
                    type: OrderStatusType
                },
                user: {
                    name: "user",
                    type: UserType,
                    resolve(source) {
                        return orderUserResolver(source);
                    }
                },
                userId: {
                    name: "userId",
                    type: GraphQLInt
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                menu: {
                    name: "menu",
                    type: new GraphQLList(new GraphQLNonNull(MenuItemType)),
                    resolve() {
                        return queryMenuResolver();
                    }
                },
                menuItem: {
                    name: "menuItem",
                    type: MenuItemType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return queryMenuItemResolver(args.id);
                    }
                },
                menuItems: {
                    name: "menuItems",
                    type: new GraphQLList(new GraphQLNonNull(MenuItemType)),
                    resolve() {
                        return queryMenuItemsResolver();
                    }
                },
                order: {
                    name: "order",
                    type: OrderType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return queryOrderResolver(args.id);
                    }
                },
                orders: {
                    name: "orders",
                    type: new GraphQLList(new GraphQLNonNull(OrderType)),
                    resolve() {
                        return queryOrdersResolver();
                    }
                },
                ordersByStatus: {
                    name: "ordersByStatus",
                    type: new GraphQLList(new GraphQLNonNull(OrderType)),
                    args: {
                        status: {
                            type: new GraphQLNonNull(OrderStatusType)
                        }
                    },
                    resolve(_source, args) {
                        return queryOrdersByStatusResolver(args.status);
                    }
                },
                user: {
                    name: "user",
                    type: UserType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return queryUserResolver(args.id);
                    }
                },
                users: {
                    name: "users",
                    type: new GraphQLList(new GraphQLNonNull(UserType)),
                    resolve() {
                        return queryUsersResolver();
                    }
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                createMenuItem: {
                    name: "createMenuItem",
                    type: MenuItemType,
                    args: {
                        category: {
                            type: new GraphQLNonNull(MenuCategoryType)
                        },
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        price: {
                            type: new GraphQLNonNull(GraphQLFloat)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateMenuItemResolver(args.name, args.price, args.category);
                    }
                },
                createOrder: {
                    name: "createOrder",
                    type: OrderType,
                    args: {
                        items: {
                            type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GraphQLInt)))
                        },
                        userId: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateOrderResolver(args.userId, args.items);
                    }
                },
                createUser: {
                    name: "createUser",
                    type: UserType,
                    args: {
                        email: {
                            type: new GraphQLNonNull(GraphQLString)
                        },
                        name: {
                            type: new GraphQLNonNull(GraphQLString)
                        }
                    },
                    resolve(_source, args) {
                        return mutationCreateUserResolver(args.name, args.email);
                    }
                },
                deleteMenuItem: {
                    name: "deleteMenuItem",
                    type: MenuItemType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationDeleteMenuItemResolver(args.id);
                    }
                },
                deleteOrder: {
                    name: "deleteOrder",
                    type: OrderType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationDeleteOrderResolver(args.id);
                    }
                },
                deleteUser: {
                    name: "deleteUser",
                    type: UserType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        }
                    },
                    resolve(_source, args) {
                        return mutationDeleteUserResolver(args.id);
                    }
                },
                updateMenuItem: {
                    name: "updateMenuItem",
                    type: MenuItemType,
                    args: {
                        category: {
                            type: MenuCategoryType
                        },
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        name: {
                            type: GraphQLString
                        },
                        price: {
                            type: GraphQLFloat
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateMenuItemResolver(args.id, args.name, args.price, args.category);
                    }
                },
                updateOrder: {
                    name: "updateOrder",
                    type: OrderType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        status: {
                            type: new GraphQLNonNull(OrderStatusType)
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateOrderResolver(args.id, args.status);
                    }
                },
                updateUser: {
                    name: "updateUser",
                    type: UserType,
                    args: {
                        email: {
                            type: GraphQLString
                        },
                        id: {
                            type: new GraphQLNonNull(GraphQLInt)
                        },
                        name: {
                            type: GraphQLString
                        }
                    },
                    resolve(_source, args) {
                        return mutationUpdateUserResolver(args.id, args.name, args.email);
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        mutation: MutationType,
        types: [DateTimeType, MenuCategoryType, OrderStatusType, MenuItemType, MutationType, OrderType, QueryType, UserType]
    });
}
